services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
      args:
        PORT: 8000
    volumes:
      - ./packages/backend/static:/app/static
    env_file:
      - ./packages/backend/.env
    environment:
      # Overwrite the port set in the .env file to ensure it matches the exposed port.
      - PORT=8000
      - OTEL_SERVICE_NAME=canvas-backend
      - OTEL_EXPORTER_OTLP_TRACES_ENDPOINT=http://jaeger:4318/v1/traces
    ports:
      - 8000:8000

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    depends_on:
      - backend
    env_file:
      - ./packages/frontend/.env
    environment:
      # 'backend' here is referencing the backend service. Docker compose automatically interprets
      # this and forwards traffic to the appropriate container.
      - NEXT_PUBLIC_API_URL=http://backend:8000
    ports:
      - 3000:3000

  opensearch:
    image: opensearchproject/opensearch:2.9.0
    environment:
      - cluster.name=opensearch-cluster
      - discovery.type=single-node
      - OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - opensearch_data:/usr/share/opensearch/data
    ports:
      - "9200:9200"

  jaeger:
    image: jaegertracing/jaeger:2.19.0
    command:
      - --config=/jaeger/config.yaml
    depends_on:
      - opensearch
    volumes:
      - ./jaeger.yaml:/jaeger/config.yaml
    ports:
      - "16686:16686"
      - "4317:4317"
      - "4318:4318"

  oauth2-proxy:
    image: quay.io/oauth2-proxy/oauth2-proxy:v7.7.1
    depends_on:
      - jaeger
    env_file:
      - ./.env.oauth
    environment:
      - OAUTH2_PROXY_REDIRECT_URL=http://jaeger.localhost/oauth2/callback
      - OAUTH2_PROXY_UPSTREAMS=http://jaeger:16686
    ports:
      - "4180:4180"

  caddy:
    image: caddy:2.7-alpine

    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    depends_on:
      - backend
      - frontend
      - oauth2-proxy
    volumes:
      # copy local ./Caddyfile to /etc/caddy/Caddyfile on docker
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data:
  caddy_config:
  opensearch_data:
