minimumReleaseAge: 10080

packages:
  - "packages/backend"
  - "packages/frontend"
  - "packages/types"

injectWorkspacePackages: true

overrides:
  protobufjs: ^7.5.5

allowBuilds:
  "@prisma/engines": false
  cpu-features: false
  esbuild: false
  prisma: false
  protobufjs: false
  sharp: false
  ssh2: false

packageExtensions:
  "sharp@0.34.5":
    dependencies:
      "@img/sharp-linuxmusl-x64": 0.34.5
      "@img/sharp-libvips-linuxmusl-x64": 1.2.4
