minimumReleaseAge: 10080

packages:
  - "packages/backend"
  - "packages/frontend"
  - "packages/types"

injectWorkspacePackages: true

overrides:
  protobufjs: ^7.5.5

allowBuilds:
  "@prisma/engines": false
  better-sqlite3: false
  cpu-features: false
  esbuild: false
  ffmpeg-static: true
  prisma: false
  protobufjs: false
  sharp: false
  ssh2: false
