minimumReleaseAge: 10080

packages:
  - "packages/backend"
  - "packages/backend-nest"
  - "packages/frontend"
  - "packages/types"

injectWorkspacePackages: true

overrides:
  protobufjs: ^7.5.5

allowBuilds:
  "@nestjs/core": false
  "@prisma/engines": false
  "@swc/core": false
  cpu-features: false
  esbuild: false
  prisma: false
  protobufjs: false
  sharp: false
  ssh2: false
